#!/usr/bin/env ruby

[
  '../text/1023.txt',
  '../text/1024.txt',
  '../text/1025.txt',
].each do |f|
  text_path = File.expand_path(f, __dir__)

  actual = `bin/tail -n 1 #{text_path}`
  expected = `tail -n 1 #{text_path}`

  if actual != expected
    warn <<-EOS
    actual  : #{actual}
    expected: #{expected}
    EOS
    exit 1
  end
end
