#!/usr/bin/env ruby

text_path = File.expand_path('../text/1023.txt', __dir__)
actual = `bin/tail -n 1 #{text_path}`
expected = `tail -n 1 #{text_path}`

if actual != expected
  warn <<-EOS
  actual  : #{actual}
  expected: #{expected}
  EOS
  exit 1
end

